wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN-GRU-MASK-FC-Classifier
dataset:
  desc: null
  value: MICAA MRI
epochs:
  desc: null
  value: 5
BATCH_SIZE:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691457870.615042
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.7
      8:
      - 1
      - 5
